server:
  port: 8090

# name? ??? ???? ??? ??? Service ID? ???
spring:
  application:
    name: MSA Gateway Server
  profiles:
    active: local
eureka:
  client:
    defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
